Update Conf and tests to reflect new stub endpoint
hmrc/transit-movements-trader-eis-router pull request #23
Opened 2021-01-13 19:01 UTC by RobertLaverick

2021-01-14 09:12 UTC, crystalmark approved these changes

2021-01-14 16:07 UTC, amaalali approved these changes

2021-01-15 09:01 UTC, crystalmark requested changes

2021-01-15 09:01 UTC, crystalmark commented on it/connectors/MessageConnectorSpec.scala
> +          ).withHeader("Authorization", equalTo("Bearer bearertokenhereGB")).willReturn(aResponse().withStatus(UNAUTHORIZED))
This'll have to be 403 Forbidden now, sorry

2021-01-18 12:28 UTC, crystalmark approved these changes

2021-01-18 15:53 UTC, merged